[package]
name = "rpydb"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rpydb"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.1"
rusqlite = { version = "0.38.0", features = ["bundled"] }
